'use client';
import { useEffect, useState } from 'react';
type Event = {id:string;title:string;date:string;location:string};
export default function GuestTickets() {
 const [events,setEvents]=useState<Event[]>([]),[eventId,setEventId]=useState(''),[email,setEmail]=useState(''),[name,setName]=useState(''),[count,setCount]=useState(1),[batch,setBatch]=useState(''),[message,setMessage]=useState(''),[busy,setBusy]=useState(false),[done,setDone]=useState(false);
 useEffect(()=>{fetch('/api/admin/guest-tickets').then(r=>r.json()).then(d=>{setEvents(d.events||[]);if(d.error)setMessage(d.error);}).catch(()=>setMessage('Veranstaltungen konnten nicht geladen werden.'));},[]);
 async function send(e:React.FormEvent) {e.preventDefault();setBusy(true);setMessage('Tickets werden erstellt und versendet …');try {const r=await fetch('/api/admin/guest-tickets',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({eventId,email,name,count,batch})});const d=await r.json();if(!r.ok)throw new Error(d.error);setDone(true);setMessage(`${d.count} Tickets an ${d.email} versendet. Versand-ID: ${d.messageId}. ${d.warning||''}`);}catch(e){setMessage(e instanceof Error?e.message:'Versand fehlgeschlagen');}finally{setBusy(false);}}
 return <main className="mx-auto max-w-xl p-8 text-white"><a href="/admin">← Adminbereich</a><h1 className="my-6 text-2xl">Gästetickets versenden</h1><p className="mb-6">Kostenlose Tickets mit einzelnen QR-Codes. Dieselbe Versandkennung bei einem erneuten Versuch beibehalten.</p><form onSubmit={send} className="grid gap-4"><label>Veranstaltung<select required value={eventId} onChange={e=>setEventId(e.target.value)} className="block w-full bg-zinc-800 p-3"><option value="">Bitte auswählen</option>{events.map(e=><option key={e.id} value={e.id}>{e.title} · {e.date} · {e.location}</option>)}</select></label><label>Empfängername<input required value={name} onChange={e=>setName(e.target.value)} className="block w-full bg-zinc-800 p-3"/></label><label>E-Mail<input required type="email" value={email} onChange={e=>setEmail(e.target.value)} className="block w-full bg-zinc-800 p-3"/></label><label>Anzahl<input required type="number" min="1" max="20" value={count} onChange={e=>setCount(Number(e.target.value))} className="block w-full bg-zinc-800 p-3"/></label><label>Versandkennung<input required minLength={8} pattern="[a-zA-Z0-9-]+" value={batch} onChange={e=>setBatch(e.target.value)} className="block w-full bg-zinc-800 p-3"/></label><button disabled={busy||done} className="rounded bg-amber-600 p-3 disabled:opacity-50">{busy?'Versand läuft …':'Gästetickets erstellen und senden'}</button></form><p role="status" className="mt-6">{message}</p></main>;
}
